const P=[
["01","DISCOVER · Problem & Research","Project Overview","FinFlow is a B2B FinTech concept for Money Transfer Operators and Payment Service Providers.","overview"],
["02","DISCOVER · Problem & Research","Problem & Audience","Multi-rail payout infrastructure creates a comprehension, control and trust problem for MTO/PSP teams.","problem"],
["02A","DISCOVER · Problem & Research","Market & Competitor Research","Reference research calibrates infrastructure storytelling and buyer-facing clarity.","research"],
["02B","DISCOVER · Problem & Research","Insights & Opportunity","Four principles shape the experience: comprehension, control, trust and conversion.","insights"],
["03","DEFINE · Product & UX Strategy","Product Strategy","FinFlow sits between payout instruction and settlement execution as one inspectable orchestration layer.","strategy"],
["04","DEFINE · Product & UX Strategy","Information Architecture","The landing is intentionally limited to three conversion-critical sections.","ia"],
["04A","DEFINE · Product & UX Strategy","User Journey","The buyer journey moves from orientation to mechanism comprehension, trust and conversion.","journey"],
["04B","DEFINE · Product & UX Strategy","Core User Flow","Paid-social traffic connects directly to product comprehension and the demo request.","flow"],
["05","DEFINE · Product & UX Strategy","Content & Conversion Strategy","Mechanism clarity first, buyer confidence second, conversion third.","content"],
["06","EXPLORE · Wireframe & Validation","Desktop Wireframe","Desktop exploration prioritizes the control-plane signature and a consolidated buyer-decision surface.","wire"],
["06A","EXPLORE · Wireframe & Validation","Mobile Wireframe","Mobile converts the network into a vertical operational stack while preserving all five rail states.","mobilewire"],
["07","DESIGN SYSTEM","Visual Foundations","Dark operational surfaces, light educational space and semantic route colors.","foundations"],
["08","DESIGN SYSTEM","Components & States","Reusable route states, tabs, buttons and operational data patterns.","components"],
["09","FINAL PRODUCT · UI & Responsive","Final Landing — Desktop","Interactive control plane, six-step mechanism and consolidated trust/conversion section.","desktop"],
["09A","FINAL PRODUCT · UI & Responsive","Route Inspector States","Wallet, Bank and Cash scenarios preserve the same control-plane grammar.","states"],
["10","FINAL PRODUCT · UI & Responsive","Final Landing — Mobile","The responsive version preserves hierarchy and operational state visibility.","mobile"],
["11","FINAL PRODUCT · UI & Responsive","Paid Social Ad — 1:1","1080×1080 ad creative reuses the same FinFlow identity and route-inspector signature.","ad"],
["12","MEASURE & DELIVER","Validation & QA","Rendered QA verifies responsive behavior, state synchronization and evidence discipline.","qa"],
["13","MEASURE & DELIVER","Success Metrics & Next Steps","Metrics are defined as post-launch hypotheses to instrument — not fabricated results.","metrics"]
];
const rail=(s="Wallet")=>'<div class="router"><div class="instruction"><small>PAYOUT INSTRUCTION</small><b>$2,840.00</b><code>USD → PHP · WALLET</code></div><div class="engine">FinFlow</div><div class="rails">'+["Bank","Wallet","Card","Stablecoin","Cash payout"].map(r=>'<div class="'+(r===s?"sel":r==="Card"?"unavail":"avail")+'"><span>'+r+'</span><em>'+(r===s?"SELECTED":r==="Card"?"UNAVAILABLE":"AVAILABLE")+'</em></div>').join("")+'</div></div>';
const body={overview:()=>'<div class="grid2"><div><p class="ey">Recruitment test · B2B FinTech</p><h2>Multi-Rail Settlement without another operational black box.</h2><p class="muted">One orchestration layer for bank, wallet, card, stablecoin and cash payout settlement.</p></div><div class="kpi"><div><b>05</b>Settlement rails</div><div><b>01</b>Orchestration layer</div><div><b>03</b>Landing sections</div></div></div><div class="cards4" style="margin-top:24px"><article><h3>Audience</h3><p>MTOs & PSPs</p></article><article><h3>Goal</h3><p>Explain + de-risk</p></article><article><h3>Deliverables</h3><p>Landing + paid social</p></article><article><h3>Direction</h3><p>Institutional · Precise · Inspectable</p></article></div>',
problem:()=>'<div class="grid2"><div><h2>More rails can create more operational ambiguity.</h2>'+["Fragmented payout paths","Low route visibility","Trust gap"].map((x,i)=>'<article><b class="accent">0'+(i+1)+'</b><h3>'+x+'</h3></article>').join("")+'</div><div class="card dark"><p class="ey">Primary audience</p><h2>MTO / PSP operator</h2><p>Needs fast comprehension, route visibility and settlement clarity.</p><p>Key question: Which rail is selected, and what state is the payout in?</p></div></div>',
research:()=>'<div class="research">'+[["Modern Treasury","Expose operational system state"],["Increase","Trust through predictable structure"],["Column","Granular control + visibility"],["Airwallex","Direct buyer-value framing"]].map(x=>'<article><h3>'+x[0]+'</h3><p class="muted">'+x[1]+'</p></article>').join("")+'</div><div class="card dark" style="margin-top:20px"><h2>Research synthesis</h2><p>One transaction in → five rails visible → one route selected → state preserved through payout.</p></div>',
insights:()=>'<div class="cards4">'+[["01","Comprehension"],["02","Control"],["03","Trust"],["04","Conversion"]].map(x=>'<article><b class="accent">'+x[0]+'</b><h3>'+x[1]+'</h3><p class="muted">'+({Comprehension:"Explain the mechanism in seconds.",Control:"Keep route and settlement state visible.",Trust:"Show inspectable behavior, not vague claims.",Conversion:"Move naturally toward a workflow demo."})[x[1]]+'</p></article>').join("")+'</div><div class="card dark" style="margin-top:22px"><p class="ey">Opportunity</p><h2>Turn multi-rail complexity into one visible decision journey.</h2></div>',
strategy:()=>'<div class="flow">'+["Payout instruction","FinFlow","5 settlement rails","Inspectable payout state"].map((x,i)=>'<div class="node '+(i===1?"focus":"")+'"><small>'+(["INPUT","ORCHESTRATION","RAILS","OUTPUT"])[i]+'</small><h3>'+x+'</h3></div>'+(i<3?'<span class="arrow">→</span>':"")).join("")+'</div><div class="cards3" style="margin-top:24px"><article><h3>One layer</h3><p>Multiple payout paths, one mental model.</p></article><article><h3>Visible state</h3><p>Selected / available / unavailable remains legible.</p></article><article><h3>Workflow demo</h3><p>Conversion asks buyers to bring a real payout journey.</p></article></div>',
ia:()=>'<div class="ia">'+[["01","Hero / Control Plane","Proposition · scenario switcher · five rail states · CTA"],["02","Six-step Mechanism","Receive → Analyze → FinFlow → Route → Settle → Payout"],["03","Trust + Outcomes + Conversion","Operating outcomes · settlement trace · request demo"]].map(x=>'<div class="node"><b>'+x[0]+'</b><b>'+x[1]+'</b><span class="muted">'+x[2]+'</span></div>').join("")+'</div>',
journey:()=>'<div class="journey">'+["Arrive","Orient","Interact","Inspect","Trust","Convert"].map((x,i)=>'<div class="node"><b class="accent">0'+(i+1)+'</b><h3>'+x+'</h3><p class="muted">'+(["Recognize audience + payout problem.","Understand one instruction → five rails.","Switch payout scenarios.","Follow the six-step mechanism.","Review visible state + principles.","Request a workflow demo."])[i]+'</p></div>').join("")+'</div>',
flow:()=>'<div class="flow">'+["1:1 Paid Social Ad","Landing Hero","Route Inspector","6-step Mechanism","Trust / Outcomes","Request Demo"].map((x,i)=>'<div class="node '+(i===5?"focus":"")+'"><h3>'+x+'</h3></div>'+(i<5?'<span class="arrow">→</span>':"")).join("")+'</div>',
content:()=>'<div class="cards3">'+[["Hero promise","One payout instruction. Five rails. One route you can inspect."],["Mechanism promise","A settlement decision should feel inspectable, not mysterious."],["Trust promise","Operational trust starts with a route your team can inspect."]].map(x=>'<article><p class="ey">'+x[0]+'</p><h2 style="font-size:28px">'+x[1]+'</h2></article>').join("")+'</div><div class="grid2" style="margin-top:22px"><div class="card"><h3>Primary CTA</h3><p>Request a workflow demo</p></div><div class="card"><h3>Evidence policy</h3><p>No fabricated metrics, certifications, customer logos or guarantees.</p></div></div>',
wire:()=>'<div class="wire"><div class="wnav"></div><div class="whero"><div class="block"></div><div class="block"></div></div><div class="wbody"><div></div><div></div></div><div class="wbody" style="background:#07111f"><div></div><div></div></div></div>',
mobilewire:()=>'<div class="phones">'+[1,2,3].map((_,i)=>'<div class="phone"><div class="box"></div><div class="box" style="height:130px"></div><div class="box" style="height:230px"></div><div class="box"></div></div>').join("")+'</div>',
foundations:()=>'<div class="grid2"><div><p class="ey">Semantic color</p><div class="swatches">'+[["#07111F","Dark shell"],["#0F1D31","Control"],["#7EA8FF","Selected"],["#6E9A7B","Available"],["#A6756E","Unavailable"]].map(x=>'<div style="--c:'+x[0]+'"><i></i><b>'+x[0]+'</b><small>'+x[1]+'</small></div>').join("")+'</div></div><div class="type"><p class="ey">Typography</p><h2>Inter Tight</h2><p>Display / headlines</p><h3>Inter</h3><p>Body / UI</p><code>IBM Plex Mono · TX 08421</code><p>Operational data</p></div></div>',
components:()=>'<div class="components"><article><p class="ey">Buttons</p><button class="btn">REQUEST A WORKFLOW DEMO ↗</button></article><article><p class="ey">Scenario tabs</p><div class="tabs"><span>Wallet payout</span><span>Bank payout</span><span>Cash pickup</span></div></article><article><p class="ey">Rail states</p><div class="rail sel">Wallet <b>SELECTED</b></div><div class="rail avail">Bank <b>AVAILABLE</b></div><div class="rail unavail">Card <b>UNAVAILABLE</b></div></article><article><p class="ey">Operational data</p><code>USD → PHP · WALLET</code><br><code>TX08421 · ROUTED</code></article></div>',
desktop:()=>'<div class="browser"><div class="bnav"><b>FinFlow</b><span>Mechanism · Trust & outcomes · Ad creative</span><button class="btn">REQUEST A DEMO ↗</button></div><div class="bhero"><div><small>MULTI-RAIL SETTLEMENT FOR MTOS & PSPS</small><h2>One payout instruction.<br><span class="accent">Five rails. One route you can inspect.</span></h2><p>One orchestration layer for bank, wallet, card, stablecoin and cash payout.</p></div>'+rail("Wallet")+'</div><div class="bleft"><h2>A settlement decision should feel inspectable, not mysterious.</h2><div class="steps">'+["Receive","Analyze","FinFlow","Route","Settle","Payout"].map((x,i)=>'<span><b class="accent">0'+(i+1)+'</b><br>'+x+'</span>').join("")+'</div></div><div style="padding:30px"><h2>Operational trust starts with a route your team can inspect.</h2></div></div>',
states:()=>'<div class="states">'+["Wallet","Bank","Cash payout"].map(x=>'<article><h3>'+x+' payout</h3>'+rail(x)+'</article>').join("")+'</div>',
mobile:()=>'<div class="phones"><div class="phone dark"><h3>FinFlow</h3><h2>One payout instruction. <span class="accent">Five rails.</span></h2>'+rail("Wallet")+'</div><div class="phone"><p class="ey">Mechanism</p><h2 style="font-size:25px">Inspectable, not mysterious.</h2>'+["Receive","Analyze","FinFlow","Route","Settle","Payout"].map((x,i)=>'<div class="card" style="padding:10px;margin:7px 0">0'+(i+1)+' · '+x+'</div>').join("")+'</div><div class="phone dark"><p class="ey">Trust + conversion</p><h2>Bring one payout journey.</h2><p>Review route, outcomes and settlement trace.</p><button class="btn">REQUEST DEMO ↗</button></div></div>',
ad:()=>'<div class="ad"><div style="display:flex;justify-content:space-between"><b>FinFlow</b><code>MTO / PSP · MULTI-RAIL</code></div><h2>Five payout rails.<br><span class="accent">One route you can inspect.</span></h2><p>Keep route choice and settlement state visible from instruction to payout.</p>'+rail("Wallet")+'<div class="adfoot"><span>Bring one payout journey.</span><button class="btn">REQUEST A WORKFLOW DEMO ↗</button></div></div>',
qa:()=>'<div class="qa">'+[["Rendered visual QA","Desktop + mobile checked for overflow and clipping."],["Scenario state sync","Wallet / Bank / Cash update rail + settlement state together."],["Responsive structure","Network collapses into a vertical operational stack."],["Evidence policy","No fake metrics, certifications or guarantees."]].map(x=>'<article><b>PASS</b><h3>'+x[0]+'</h3><p class="muted">'+x[1]+'</p></article>').join("")+'</div>',
metrics:()=>'<div class="metrics">'+[["Comprehension","Measure route-inspector + mechanism interactions."],["Intent","Track qualified demo CTA progression."],["Friction","Find drop-off before the trust section."]].map(x=>'<article><p class="ey">'+x[0]+'</p><h3>'+x[1]+'</h3></article>').join("")+'</div><div class="next"><p class="ey">Next iteration</p>'+["User-test terminology with MTO/PSP operators.","Validate routing context shown in control plane.","Instrument interaction + CTA events.","Revise from observed behavior."].map((x,i)=>'<div><b class="accent">0'+(i+1)+'</b> · '+x+'</div>').join("")+'</div>'
};
const qs=new URLSearchParams(location.search);const id=qs.get("frame");
const logo='<a class="brand" href="./"><img src="../assets/finflow-mark.svg"><span>FinFlow</span></a>';
function hub(){const groups=[["01 — DISCOVER",P.slice(0,4)],["02 — DEFINE",P.slice(4,9)],["03 — EXPLORE",P.slice(9,11)],["04 — DESIGN SYSTEM",P.slice(11,13)],["05 — FINAL PRODUCT",P.slice(13,17)],["06 — MEASURE & DELIVER",P.slice(17,19)]];return '<div class="canvas"><header class="top">'+logo+'<div class="meta"><span>Figma conversion pack</span><b>19 frames</b></div></header><main class="hub"><p class="ey">FINFLOW · CASE STUDY SYSTEM</p><h1>19-page Figma Pack</h1><p>Open any frame as its own URL for HTML → Figma conversion.</p>'+groups.map(g=>'<section class="group"><h2>'+g[0]+'</h2><div class="links">'+g[1].map(p=>'<a href="?frame='+p[0]+'"><b>'+p[0]+'</b><span>'+p[2]+'</span></a>').join("")+'</div></section>').join("")+'</main></div>'}
function render(p){return '<div class="canvas"><header class="top">'+logo+'<div class="meta"><span>'+p[1]+'</span><b>'+p[0]+'</b></div></header><main class="content"><div class="head"><div class="code">'+p[0]+'</div><div><h1>'+p[2]+'</h1><p>'+p[3]+'</p></div></div>'+body[p[4]]()+'</main></div>'}
document.getElementById("app").innerHTML=id?render(P.find(p=>p[0].toLowerCase()===id.toLowerCase())||P[0]):hub();